# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-24 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='message',
            field=models.CharField(max_length=500),
        ),
    ]
