# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-24 13:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20151224_1248'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='message',
            new_name='jmessage',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='school_name',
            new_name='sch_name',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='subject',
            new_name='subj',
        ),
    ]
