# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-22 15:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_auto_20151222_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='school_photo',
            field=models.ImageField(default=datetime.datetime(2015, 12, 22, 15, 49, 5, 200928, tzinfo=utc), upload_to=''),
            preserve_default=False,
        ),
    ]
