# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-22 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_school_school_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='school_photo',
            field=models.ImageField(upload_to='school_photos'),
        ),
    ]
